# -*- coding: utf-8 -*-
"""Read File

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSZQX4ArXjOPedwfuspAuUH47LgAIFyO
"""

def read_file(path):
  with open(path) as input_file:
      # Get all lines from input file
      lines = [line for line in input_file]
    
      # Convert line to attribute
      width, height = [int(x) for x in lines[0].split()]
      start_x, start_y, end_x, end_y = [int(x) for x in lines[1].split()]
    
      # Get number of polygons
      number_of_polygons = int(lines[2])
    
      # Get polygons
      length = len(lines)
      polygons = [[int(x) for x in lines[i].split()] for i in range(3, length)]
    
      # Convert type of polygons from list of list to list of list of tuple
      new_polygons = []
      for polygon in polygons:
        temp_polygon = []
      
        for i in range(len(polygon)):
          if i % 2 == 0:
            x = polygon[i]
          
          if i % 2 == 1:
            y = polygon[i]
            temp_polygon.append((x, y))
          
        new_polygons.append(temp_polygon)
        
  return width, height, (start_x, start_y), (end_x, end_y), new_polygons